// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// blockLevelRead
List blockLevelRead(std::string fname);
RcppExport SEXP R3_blockLevelRead(SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    __result = Rcpp::wrap(blockLevelRead(fname));
    return __result;
END_RCPP
}
// readStructurized
List readStructurized(std::string fname);
RcppExport SEXP R3_readStructurized(SEXP fnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fname(fnameSEXP);
    __result = Rcpp::wrap(readStructurized(fname));
    return __result;
END_RCPP
}
