# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blockLevelRead <- function(fname) {
    .Call('R3_blockLevelRead', PACKAGE = 'R3', fname)
}

readStructurized <- function(fname) {
    .Call('R3_readStructurized', PACKAGE = 'R3', fname)
}

